# docker-compose.yml
services:
  telegram-job-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-job-bot
    restart: unless-stopped
    env_file:
      - bot-secrets.env
    volumes:
      - bot_data:/app/data
      - bot_logs:/app/logs
    # Resource limits optimized for 552MB RAM system
    deploy:
      resources:
        limits:
          memory: 400M
          cpus: '0.9'
        reservations:
          memory: 200M
          cpus: '0.2'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - bot-network

volumes:
  bot_data:
  bot_logs:

networks:
  bot-network:
    driver: bridge
